# fly.toml app configuration file generated for hidden-violet-6754 on 2023-08-20T00:37:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hidden-violet-6754"
primary_region = "sin"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
